### ISSUE TITLE
Example code from mario_gpt should possibly be mario_gpt.lm

### ISSUE THREAD

**Issue by mossly** [shyamsn97/mario-gpt#5]
Hi, 

First of all thanks for your novel implementation! _This is very cool to see._ 

When running the minimal code snippet provided in the readme, I got the following error: 

```
C:\Users\Mossly\Desktop>py mariotest.py
Traceback (most recent call last):
  File "C:\Users\Mossly\Desktop\mariotest.py", line 1, in <module>
    from mario_gpt import MarioLM
ImportError: cannot import name 'MarioLM' from 'mario_gpt' (C:\Users\Mossly\AppData\Local\Programs\Python\Python310\lib\site-packages\mario_gpt\__init__.py)
```

I resolved it by changing the line: 
`from mario_gpt import MarioLM`
**to**
`from mario_gpt.lm import MarioLM`

Perhaps this is just a simple syntactical mistake? Or it could be user error on my part... 

Thanks for your attention!

**Comment by shyamsn97** [comment]
Hey! So I actually updated the code to make this importing possible, but I realized that the pypi package has not really been updated yet. I reverted this back in the README so it should be good :)

**Comment by mossly** [comment]
Thanks for your assistance! 

I'm pretty close to getting things working but hit another error I've been unable to debug. 

generated_level = mario_lm.sample(
  File "lm.py", line 113, in sample
    [self.prompter.output_hidden(prompt) for prompt in prompts]
  File "lm.py", line 113, in <listcomp>
    [self.prompter.output_hidden(prompt) for prompt in prompts]
  File "prompter.py", line 117, in output_hidden
    .mean(0)
AttributeError: 'list' object has no attribute 'mean'

This is using the default prompts = ["many pipes", "many enemies", "some blocks", "high elevation"]

Any help would be greatly appreciated!

**Comment by shyamsn97** [comment]
Hey! So multiple prompts should now work. You should probably clone the repo or update from pypi. On another note, when using default prompts make sure you're using:

prompts = ["many pipes, many enemies, some blocks, high elevation"]

instead of

prompts = ["many pipes", "many enemies", "some blocks", "high elevation"]

If you split the categories the model could still work, but I haven't tested that out extensively.

**Comment by shyamsn97** [comment]
Also, make sure you update your `transformers` package :)

**Comment by shyamsn97** [comment]
Thanks for pointing this out though, lmk if there's any other errors!

**Comment by mossly** [comment]
I updated the repo, transformers, fixed up the prompts as per your advice, and now everything is working on Windows 11 with Python 3.10. 

Thanks again for all your help! :)

![level](https://user-images.githubusercontent.com/7801296/219265067-e0053fd6-9bb9-4805-bcb4-c9d2470c7cc2.jpg)
